# Generated by Django 3.2.9 on 2021-11-12 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('demo_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('source_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
